---
title: Peace Corps Tanzania
timezone: UTC
collections:
  committees:
    title: Committees
    output: true
  posts:
    title: Posts
    output: true
  sectory:
    title: Sectory
    output: true
  uploads:
    title: Uploads
    output: true
  volunteer-life:
    title: Volunteer Life
    output: true
description: 
email: pctzict@gmail.com
baseurl: "/pctz"
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
plugins:
- jekyll-feed
