---
title: Peace Corps Tanzania
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: pctzict@gmail.com
description: 
baseurl: "/pctz"
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
remote_theme: mmistakes/so-simple-theme
plugins:
- jekyll-feed
